#spring.application.name=likelion-assignment-crud

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likelion_crud   # ??? MySQL ??????? ??
    username: root                                   # ?? MySQL ??? ??
    password: 1234                                # ?? MySQL ????
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ???? ???

  jpa:
    hibernate:
      ddl-auto: update     # ??? ?? ?? (create, update, validate, none ? ? 1)
    show-sql: true         # ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: true   # SQL ??? ?? ?? ?? (???)
        show_sql: true     # ??? ???? SQL ??? ???
    open-in-view: false    # OSIV(Open Session In View) ????

logging:
  level:
    org.hibernate.SQL: debug                  # ???? SQL ?? ??
    org.hibernate.type.descriptor.sql: trace  # ???? ???? ? ?? ??
